"""Corrections to footprints generated by easyeda2kicad (idempotent; run after generating new ones).

* USB4105-GF-A: the two 0.65 mm positioning posts are plated holes with no copper ring in the EasyEDA
  footprint; GCT's drawing shows them as 2x 0.65 mm posts, so they become unplated (NPTH) holes.
"""
import re
from pathlib import Path

LIB = Path(__file__).resolve().parent.parent / "lib" / "lcsc" / "lcsc.pretty"


def fix_usb():
    f = LIB / "TYPE-C-SMD_SBC-160S1A-20-S412.kicad_mod"
    t = f.read_text(encoding="utf-8")
    new, n = re.subn(r'\(pad ""?\s*thru_hole circle(\s+\(at [-\d. ]+\)\s+\(size 0\.65 0\.65\))',
                     r'(pad "" np_thru_hole circle\1', t)
    if n:
        f.write_text(new, encoding="utf-8")
    print(f"{f.name}: {n} positioning posts converted to NPTH")


if __name__ == "__main__":
    fix_usb()
